### ISSUE TITLE
Error on windows 10 version 2004

### ISSUE THREAD

**Issue by dev-2null** [b4rtik/SharpMiniDump#1]
```
[*] OS MajorMinor version : 10.0

Unhandled Exception: System.ComponentModel.Win32Exception: Incorrect function
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.ProcessManager.GetModuleInfos(Int32 processId)
   at System.Diagnostics.Process.get_Modules()
   at SharpMiniDump.CustomLoadLibrary.GetLoadedModuleAddress(String DLLName)
   at SharpMiniDump.CustomLoadLibrary.GetDllAddress(String DLLName, Boolean CanLoadFromDisk)
   at SharpMiniDump.Natives.LoadLibrary(String name)
   at SharpMiniDump.Natives.GetKernelbase()
   at SharpMiniDump.Natives.VirtualProtect(IntPtr lpAddress, UIntPtr dwSize, UInt32 flNewProtect, UInt32& lpflOldProtect)
   at SharpMiniDump.NativeSysCall.ZwProtectVirtualMemory10(IntPtr hProcess, IntPtr& lpBaseAddress, UInt32& NumberOfBytesToProtect, UInt32 NewAccessProtection, UInt32& lpNumberOfBytesWritten)
   at SharpMiniDump.Program.UnHookNativeApi(WIN_VER_INFO pWinVerInfo)
   at SharpMiniDump.Program.Execute(String[] args)
   at SharpMiniDump.Program.Main(String[] args)
```

**Comment by b4rtik** [comment]
I would have bet that the number of the syscall had changed ... it's not like that ... let's see

**Comment by b4rtik** [comment]
```
Z:\source\repos\DotNet\SharpMiniDump\SharpMiniDump\bin\Release>SharpMiniDump.exe
[*]
[*]                     System Information
[*] ----------------------------------------------------------------------
[*] | Platform: Win32NT                                                  |
[*] ----------------------------------------------------------------------
[*] | Major: 10            | Minor: 0             | Build: 19041         |
[*] ----------------------------------------------------------------------
[*] | Version: Microsoft Windows NT 6.2.9200.0                           |
[*] ----------------------------------------------------------------------
[*]
[*] ZwOpenProcess10  Wait0
[*] PssCaptureSnapshot 0
[*] Target PID 764
[*] Generating minidump.... 764
[*] End
[*] Minidump generated in  C:\Windows\Temp\dumpert.dmp
```

Could you give me some more information about your environment?

**Comment by dev-2null** [comment]
Hi, it's Microsoft Windows 10 Pro (10.0.19041 N/A Build 19041). 
Version 2004 OS Build 19041.388
Thanks!

**Comment by b4rtik** [comment]
I can't reproduce the error in a fresh Windows 10 2004 installation.

Which user are you running the tool with?
Is there an AV other than Defender installed?
What configuration did you compile the assembly with?
Are you running the command line tool or through a C2?
What .Net frameworks are installed on the machine?

**Comment by dev-2null** [comment]
Interesting... the falcon sensor didn't give me any kind of warning but it works without falcon sensor installed. Any idea why?
